apiVersion: v1
kind: Service
metadata:
  name: mongodb-shardX-service
  labels:
    name: mongodb-shardX
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb-shardX
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod-shardX
spec:
  serviceName: mongodb-shardX-service
  replicas: 2
  template:
    metadata:
      labels:
        role: mongodb-shardX
        tier: maindb
        replicaset: ShardXRepSet
        replicasetRole: ShardXRepSetShard
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: replicaset
                operator: In
                values:
                - ShardXRepSet
              matchExpressions:
              - key: tier
                operator: In
                values:
                - maindb
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      volumes:
        - name: secrets-volume
          secret:
            secretName: shared-bootstrap-data
            defaultMode: 256
      nodeSelector:
        mongo-node: shard
      containers:
        - name: mongod-shardX-container
          image: mongo:3.4.10
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--port"
            - "27017"
            - "--wiredTigerCacheSizeGB"
            - "0.25"
            - "--shardsvr"
            - "--replSet"
            - "ShardXRepSet"
            - "--auth"
            - "--clusterAuthMode"
            - "keyFile"
            - "--keyFile"
            - "/etc/secrets-volume/internal-auth-mongodb-keyfile"
            - "--setParameter"
            - "authenticationMechanisms=SCRAM-SHA-1"
          resources:
            requests:
              cpu: MAINDB_CPU
              memory: MAINDB_RAM
            limits:
              cpu: MAINDB_LIM_CPU
              memory: MAINDB_LIM_RAM
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
            - name: mongo-shardX-persistent-storage-claim
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-shardX-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
