apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod-shardX-arbiter
spec:
  serviceName: mongodb-shardX-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-shardX
        tier: arbiter
        replicaset: ShardXRepSet
        replicasetRole: ShardXRepSetArb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: replicaset
                operator: In
                values:
                - ShardXRepSet
              matchExpressions:
              - key: tier
                operator: In
                values:
                - arbiter
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      volumes:
        - name: secrets-volume
          secret:
            secretName: shared-bootstrap-data
            defaultMode: 256
      nodeSelector:
        mongo-node: shard
      containers:
        - name: mongod-arbiter-container
          image: mongo:3.4.10
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--port"
            - "27017"
            - "--wiredTigerCacheSizeGB"
            - "0.25"
            - "--shardsvr"
            - "--replSet"
            - "ShardXRepSet"
            - "--auth"
            - "--clusterAuthMode"
            - "keyFile"
            - "--keyFile"
            - "/etc/secrets-volume/internal-auth-mongodb-keyfile"
            - "--setParameter"
            - "authenticationMechanisms=SCRAM-SHA-1"
          resources:
            requests:
              cpu: ARBITER_CPU
              memory: ARBITER_RAM
            limits:
              cpu: ARBITER_LIM_CPU
              memory: ARBITER_LIM_RAM
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
